Repository KatLab-MiyazakiUniv/etrobocon2019, pull requests merged in 2019-10, with the labels that each got.

#245 ﾎﾞｰﾅｽﾀｲﾑが間違ってたので修正した
  README.md
Labels: TODO

#240 closed #239 LコースとRコースのPID値を切り替えられるようにした
  src/module/LineTracer.h
  src/module/NormalCourse.cpp
  src/module/Pid.cpp
  src/module/Pid.h
Labels: 機能要求

#241 closed #232 ライントレース時に速度制御を行わないようにした
  src/module/LineTracer.cpp
  src/module/NormalCourse.cpp
Labels: 信頼性

#250 closed #247 キャリブレーション時にアームの初期位置調整する関数を追加
  src/module/Calibrator.cpp
  src/module/Calibrator.h
  src/module/Navigator.cpp
  src/module/Navigator.h
  src/module/api/core/Controller.cpp
  src/module/api/core/Controller.h
  test/CalibratorTest.cpp
  test/dummy/Controller.h
Labels: 機能向上
